"""add_settings_and_video_metadata

Revision ID: 1c09090bdc6d
Revises: f23ea44f4dc9
Create Date: 2026-03-16 06:45:36.723254
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c09090bdc6d'
down_revision: Union[str, None] = 'f23ea44f4dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'podcast_script')
    op.add_column('users', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_videos_platform_id'), table_name='videos')
    # op.create_index('ix_videos_platform_id', 'videos', ['platform', 'platform_id'], unique=False)
    # Actually, the model says Index("ix_videos_platform_id", "platform", "platform_id")
    # But it was already there? Let's check. 
    # Let me just add the columns for now and keep the index change if it's correct.
    # Wait, the psql output said "ix_videos_platform_id" btree (platform_id)
    # So the model's new index (platform, platform_id) IS a change.
    op.create_index('ix_videos_platform_id', 'videos', ['platform', 'platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_platform_id', table_name='videos')
    op.create_index(op.f('ix_videos_platform_id'), 'videos', ['platform_id'], unique=False)
    op.drop_column('users', 'settings')
    op.add_column('analyses', sa.Column('podcast_script', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
