"""add podcast to analysis

Revision ID: 610c8c03280d
Revises: 1c09090bdc6d
Create Date: 2026-03-17 00:08:18.479374
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610c8c03280d'
down_revision: Union[str, None] = '1c09090bdc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('podcast', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'podcast')
    # ### end Alembic commands ###
