"""add progress tracking columns

Revision ID: 822f9075a121
Revises: 655fcc769d3f
Create Date: 2026-03-15 16:37:40.220296
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822f9075a121'
down_revision: Union[str, None] = '655fcc769d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('progress_percentage', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('videos', sa.Column('progress_percentage', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'progress_percentage')
    op.drop_column('analyses', 'progress_percentage')
    # ### end Alembic commands ###
