"""Add user_notes to Analysis

Revision ID: 95ccf28cb8df
Revises: fbd63be88f4f
Create Date: 2026-03-16 23:10:20.328123
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ccf28cb8df'
down_revision: Union[str, None] = 'fbd63be88f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('user_notes', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_videos_platform_id'), table_name='videos')
    op.create_index('ix_videos_platform_id', 'videos', ['platform', 'platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_platform_id', table_name='videos')
    op.create_index(op.f('ix_videos_platform_id'), 'videos', ['platform_id'], unique=False)
    op.drop_column('analyses', 'user_notes')
    # ### end Alembic commands ###
