"""add_estimation_and_full_analysis

Revision ID: f23ea44f4dc9
Revises: 822f9075a121
Create Date: 2026-03-15 11:40:41.625935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23ea44f4dc9'
down_revision: Union[str, None] = '822f9075a121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('estimated_remaining_seconds', sa.Integer(), nullable=True))
    # Add as nullable first
    op.add_column('analyses', sa.Column('full_analysis', sa.Boolean(), nullable=True))
    # Provide a default for existing rows
    op.execute("UPDATE analyses SET full_analysis = FALSE")
    # Now set as NOT NULL
    op.alter_column('analyses', 'full_analysis', nullable=False)
    
    op.add_column('videos', sa.Column('estimated_remaining_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'estimated_remaining_seconds')
    op.drop_column('analyses', 'full_analysis')
    op.drop_column('analyses', 'estimated_remaining_seconds')
    # ### end Alembic commands ###
