"""Add glossary and resources to Analysis

Revision ID: fbd63be88f4f
Revises: 610c8c03280d
Create Date: 2026-03-16 22:53:16.670827
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbd63be88f4f'
down_revision: Union[str, None] = '610c8c03280d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('glossary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_videos_platform_id'), table_name='videos')
    op.create_index(op.f('ix_videos_platform_id'), 'videos', ['platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_platform_id'), table_name='videos')
    op.create_index(op.f('ix_videos_platform_id'), 'videos', ['platform', 'platform_id'], unique=False)
    op.drop_column('analyses', 'resources')
    op.drop_column('analyses', 'glossary')
    # ### end Alembic commands ###
